name: CI

on:
  push:
    branches:
      - main  # Adjust if your default branch is not main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile C program
        run: gcc -o github_actions_program github_actions_program.c
      - name: Run program
        run: ./github_actions_program
